# Generated by Django 3.1 on 2020-08-26 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名前')),
                ('url', models.URLField(max_length=40, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='InfoSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名前')),
                ('url', models.URLField(max_length=40, verbose_name='url')),
                ('individual', models.BooleanField(default=True, max_length=40, verbose_name='個人サイト')),
            ],
        ),
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='サイトタイプ')),
            ],
        ),
        migrations.CreateModel(
            name='Tarent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=40, verbose_name='芸名。無いなら、芸能ニュースなどでの呼称')),
                ('family_name', models.CharField(max_length=40, verbose_name='性(漢字)漢字が無い外国人ならカタカナ')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='名(漢字)漢字が無い外国人ならカタカナ')),
                ('family_katakana_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='セイ(カナ)')),
                ('first_katakana_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='メイ(カナ)')),
                ('family_rome_name', models.CharField(max_length=40, verbose_name='性(ローマ字)')),
                ('first_rome_name', models.CharField(max_length=40, verbose_name='名(ローマ字)')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='誕生日(分からなければ空欄)')),
                ('charm_point', models.CharField(blank=True, max_length=40, null=True, verbose_name='良い点👍')),
            ],
        ),
        migrations.CreateModel(
            name='TarentArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='作品名')),
                ('title_img', models.CharField(blank=True, max_length=40, null=True, verbose_name='タイトル画像')),
                ('good_point', models.CharField(blank=True, max_length=40, null=True, verbose_name='良い点👍')),
                ('bad_point', models.CharField(blank=True, max_length=40, null=True, verbose_name='悪い点👎')),
                ('published_date', models.DateField(verbose_name='出版日')),
                ('tarent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tarent', verbose_name='タレント')),
            ],
        ),
        migrations.CreateModel(
            name='TarentArtFetishism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='フェチ名')),
            ],
        ),
        migrations.CreateModel(
            name='TarentBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='ボディ')),
            ],
        ),
        migrations.CreateModel(
            name='TarentBraSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, verbose_name='ブラのサイズ')),
            ],
        ),
        migrations.CreateModel(
            name='TarentFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='顔の傾向')),
            ],
        ),
        migrations.CreateModel(
            name='TarentLowerBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='下半身')),
            ],
        ),
        migrations.CreateModel(
            name='TarentPersonality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='性格')),
            ],
        ),
        migrations.CreateModel(
            name='TarentUpperBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='上半身')),
            ],
        ),
        migrations.CreateModel(
            name='TarentTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=40, verbose_name='ISBNコード')),
                ('title', models.CharField(max_length=40, verbose_name='署名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('publisher', models.CharField(choices=[('集英社', '集英社')], max_length=40, verbose_name='出版社')),
                ('draft', models.BooleanField(default=True, verbose_name='下書き(チェックを外すと公開されます。)')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='公開日時')),
                ('tarent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tarent', verbose_name='タレント')),
            ],
        ),
        migrations.CreateModel(
            name='TarentSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='url')),
                ('site_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.sitetype', verbose_name='サイトのタイプ')),
                ('tarent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tarent', verbose_name='タレント')),
            ],
        ),
        migrations.CreateModel(
            name='TarentArtSampleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=40, verbose_name='サンプル画像url')),
                ('html', models.CharField(max_length=40, verbose_name='サンプル画像html')),
                ('sort', models.IntegerField(default=0, verbose_name='表示順')),
                ('affiliate_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.affiliateprovider', verbose_name='サンプル画像提供元')),
                ('tarent_art', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tarentart', verbose_name='作品名')),
            ],
        ),
        migrations.CreateModel(
            name='TarentArtInfoSiteArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=40, verbose_name='url')),
                ('info_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.infosite', verbose_name='情報サイト名')),
                ('tarent_art', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.tarentart', verbose_name='紹介作品')),
            ],
        ),
        migrations.AddField(
            model_name='tarentart',
            name='tarent_art_fetishism',
            field=models.ManyToManyField(to='api.TarentArtFetishism', verbose_name='フェチ名'),
        ),
        migrations.AddField(
            model_name='tarent',
            name='tarent_body',
            field=models.ManyToManyField(to='api.TarentBody', verbose_name='ボディ'),
        ),
        migrations.AddField(
            model_name='tarent',
            name='tarent_bra_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.tarentbrasize', verbose_name='ブラのサイズ'),
        ),
        migrations.AddField(
            model_name='tarent',
            name='tarent_face',
            field=models.ManyToManyField(to='api.TarentFace', verbose_name='顔の傾向'),
        ),
        migrations.AddField(
            model_name='tarent',
            name='tarent_lower_body',
            field=models.ManyToManyField(to='api.TarentLowerBody', verbose_name='下半身'),
        ),
        migrations.AddField(
            model_name='tarent',
            name='tarent_personality',
            field=models.ManyToManyField(to='api.TarentPersonality', verbose_name='性格(こっちから見えるでよい。)'),
        ),
        migrations.AddField(
            model_name='tarent',
            name='tarent_upper_body',
            field=models.ManyToManyField(to='api.TarentUpperBody', verbose_name='上半身'),
        ),
    ]
