# Generated by Django 3.1 on 2020-08-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarentInfoSiteEmbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.CharField(max_length=2000, verbose_name='embed_html')),
                ('sort', models.IntegerField(default=0, verbose_name='表示順')),
                ('site_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.sitetype', verbose_name='サイトのタイプ')),
                ('tarent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tarent', verbose_name='タレント')),
            ],
        ),
    ]
