# Generated by Django 3.1 on 2020-08-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tarentinfositeembed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarentinfositeembed',
            name='html',
            field=models.TextField(max_length=2000, verbose_name='embed_html'),
        ),
    ]
