# Generated by Django 3.1 on 2020-08-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200828_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarentinfositeembed',
            name='html',
            field=models.TextField(max_length=4000, verbose_name='embed_html'),
        ),
    ]
