# Generated by Django 3.1 on 2020-08-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200828_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarentinfositeembed',
            name='html',
            field=models.TextField(max_length=8000, verbose_name='embed_html'),
        ),
    ]
