# Generated by Django 3.1 on 2020-08-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tarentbrasize_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarentface',
            name='memo',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='顔についてメモ'),
        ),
    ]
