# Generated by Django 3.1 on 2020-08-29 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tarentface_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarenttimeline',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='tarenttimeline',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='tarenttimeline',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tarenttimeline',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='tarenttimeline',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='tarenttimeline',
            name='title',
        ),
        migrations.AddField(
            model_name='tarenttimeline',
            name='html',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='埋め込みhtml'),
        ),
        migrations.AddField(
            model_name='tarenttimeline',
            name='site_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.sitetype', verbose_name='サイトのタイプ'),
        ),
        migrations.AddField(
            model_name='tarenttimeline',
            name='url',
            field=models.URLField(blank=True, max_length=40, null=True, verbose_name='timelineへのurl'),
        ),
    ]
