# Generated by Django 3.1 on 2020-08-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tarent_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarent',
            name='image',
            field=models.URLField(blank=True, max_length=40, null=True, verbose_name='url'),
        ),
    ]
