# Generated by Django 3.1 on 2020-08-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tarent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarent',
            name='image',
            field=models.URLField(blank=True, max_length=80, null=True, verbose_name='画像へのurl'),
        ),
    ]
