# Generated by Django 3.1 on 2020-09-03 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200830_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='JavPop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=80, unique=True, verbose_name='タイトル')),
                ('image', models.TextField(blank=True, max_length=80, null=True, unique=True, verbose_name='パッケージ画像へのurl')),
                ('art_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='ビデオ番号')),
                ('tarent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.tarent', verbose_name='タレント名')),
            ],
        ),
        migrations.CreateModel(
            name='JavPopLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_link', models.CharField(max_length=60, verbose_name='ビデオ番号')),
                ('javpop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.javpop', verbose_name='')),
            ],
        ),
    ]
