# Generated by Django 3.1 on 2020-09-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_javpop_javpoplink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarent',
            name='family_katakana_name',
            field=models.CharField(max_length=40, verbose_name='セイ(カナ)'),
        ),
        migrations.AlterField(
            model_name='tarent',
            name='first_katakana_name',
            field=models.CharField(max_length=40, verbose_name='メイ(カナ)'),
        ),
        migrations.AlterField(
            model_name='tarent',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='名(漢字)漢字が無い外国人ならカタカナ'),
        ),
        migrations.AlterField(
            model_name='tarent',
            name='stage_name',
            field=models.CharField(max_length=40, unique=True, verbose_name='芸名。無いなら、芸能ニュースなどでの呼称'),
        ),
    ]
