# Generated by Django 3.1 on 2020-08-24 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=40, verbose_name='芸名。無いなら、芸能ニュースなどでの呼称')),
                ('family_name', models.CharField(max_length=40, verbose_name='性(漢字)漢字が無い外国人ならカタカナ')),
                ('family_rome_name', models.CharField(max_length=40, verbose_name='性(ローマ字)')),
                ('first_rome_name', models.CharField(max_length=40, verbose_name='名(ローマ字)')),
            ],
        ),
        migrations.CreateModel(
            name='TarentTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=40, verbose_name='ISBNコード')),
                ('title', models.CharField(max_length=40, verbose_name='署名')),
                ('price', models.IntegerField(max_length=40, verbose_name='価格')),
                ('publisher', models.CharField(choices=[('集英社', '集英社')], max_length=40, verbose_name='出版社')),
                ('draft', models.BooleanField(default=True, verbose_name='下書き')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='公開日時')),
                ('tarent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.tarent', verbose_name='タレント')),
            ],
        ),
        migrations.CreateModel(
            name='TarentSNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='url')),
                ('sns_type', models.CharField(choices=[('twitter', 'twitter'), ('instagram', 'instagram'), ('youtube', 'youtube'), ('その他のSNS', 'その他のSNS')], max_length=40, verbose_name='出版社')),
                ('tarent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.tarent', verbose_name='タレント')),
            ],
        ),
    ]
