# Generated by Django 3.1 on 2020-08-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200825_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarentartfetishism',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='tarentartfetishism',
            name='tarent',
        ),
        migrations.AddField(
            model_name='tarentartfetishism',
            name='TarentArt',
            field=models.ManyToManyField(to='blog.TarentArt', verbose_name='作品名'),
        ),
    ]
