# Generated by Django 3.1 on 2020-08-24 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200825_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarentartfetishism',
            name='TarentArt',
        ),
        migrations.AddField(
            model_name='tarent',
            name='tarent_body',
            field=models.ManyToManyField(blank=True, null=True, to='blog.TarentBody', verbose_name='ボディ'),
        ),
        migrations.AddField(
            model_name='tarent',
            name='tarent_bra_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.tarentbrasize', verbose_name='ブラのサイズ'),
        ),
        migrations.AddField(
            model_name='tarent',
            name='tarent_face',
            field=models.ManyToManyField(blank=True, null=True, to='blog.TarentFace', verbose_name='顔の傾向'),
        ),
        migrations.AddField(
            model_name='tarent',
            name='tarent_lower_body',
            field=models.ManyToManyField(blank=True, null=True, to='blog.TarentLowerBody', verbose_name='下半身'),
        ),
        migrations.AddField(
            model_name='tarent',
            name='tarent_personality',
            field=models.ManyToManyField(blank=True, null=True, to='blog.TarentPersonality', verbose_name='性格(こっちから見えるでよい。)'),
        ),
        migrations.AddField(
            model_name='tarent',
            name='tarent_upper_body',
            field=models.ManyToManyField(blank=True, null=True, to='blog.TarentUpperBody', verbose_name='上半身'),
        ),
        migrations.AddField(
            model_name='tarentart',
            name='tarent_art_fetishism',
            field=models.ManyToManyField(blank=True, null=True, to='blog.TarentArtFetishism', verbose_name='フェチ名'),
        ),
        migrations.AlterField(
            model_name='tarentartfetishism',
            name='name',
            field=models.CharField(max_length=40, verbose_name='フェチ名'),
        ),
        migrations.AlterField(
            model_name='tarentpersonality',
            name='name',
            field=models.CharField(max_length=40, verbose_name='性格'),
        ),
    ]
