# Generated by Django 3.1 on 2020-08-24 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200825_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarentart',
            name='bad_point',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='悪い点👎'),
        ),
        migrations.AddField(
            model_name='tarentart',
            name='good_point',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='良い点👍'),
        ),
        migrations.AlterField(
            model_name='tarent',
            name='tarent_body',
            field=models.ManyToManyField(to='blog.TarentBody', verbose_name='ボディ'),
        ),
        migrations.AlterField(
            model_name='tarent',
            name='tarent_face',
            field=models.ManyToManyField(to='blog.TarentFace', verbose_name='顔の傾向'),
        ),
        migrations.AlterField(
            model_name='tarent',
            name='tarent_lower_body',
            field=models.ManyToManyField(to='blog.TarentLowerBody', verbose_name='下半身'),
        ),
        migrations.AlterField(
            model_name='tarent',
            name='tarent_personality',
            field=models.ManyToManyField(to='blog.TarentPersonality', verbose_name='性格(こっちから見えるでよい。)'),
        ),
        migrations.AlterField(
            model_name='tarent',
            name='tarent_upper_body',
            field=models.ManyToManyField(to='blog.TarentUpperBody', verbose_name='上半身'),
        ),
        migrations.AlterField(
            model_name='tarentsite',
            name='site_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.sitetype', verbose_name='サイトのタイプ'),
        ),
    ]
