# Generated by Django 3.1 on 2020-08-24 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200825_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名前')),
                ('url', models.URLField(max_length=40, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='InfoSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名前')),
                ('url', models.URLField(max_length=40, verbose_name='url')),
                ('individual', models.BooleanField(default=True, max_length=40, verbose_name='個人サイト')),
            ],
        ),
        migrations.AddField(
            model_name='tarentart',
            name='title_img',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='タイトル画像'),
        ),
        migrations.AlterField(
            model_name='tarentart',
            name='tarent_art_fetishism',
            field=models.ManyToManyField(to='blog.TarentArtFetishism', verbose_name='フェチ名'),
        ),
        migrations.CreateModel(
            name='TarentArtSampleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=40, verbose_name='サンプル画像url')),
                ('html', models.CharField(max_length=40, verbose_name='サンプル画像html')),
                ('affiliate_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.affiliateprovider', verbose_name='サンプル画像提供元')),
                ('tarent_art', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.tarentart', verbose_name='作品名')),
            ],
        ),
        migrations.CreateModel(
            name='TarentArtInfoSiteArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=40, verbose_name='url')),
                ('info_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.infosite', verbose_name='情報サイト名')),
            ],
        ),
    ]
