# Generated by Django 3.1 on 2020-08-24 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200825_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarentartinfositearticle',
            name='tarent_art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.tarentart', verbose_name='紹介作品'),
        ),
    ]
