# Generated by Django 3.1 on 2020-08-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200825_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarentartsampleimage',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='表示順'),
        ),
    ]
